version: "3.8"
services:
  app:
    build:
      context: .
    volumes:
      - .:/timetables_trail_system
    ports:
      - 3000:3000
    image: timetable_app:timetable_app
    container_name: timetable_app_container
    command: npm start
